"""
Django settings for chirp project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_27eto_6&*cz6cx26valns6lqv*v4am224r3j9y5@hoz*58=_-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS_STR = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(",")]
VERISAFE_API_SECRET = os.getenv("VERISAFE_API_SECRET", "")

VERISAFE_SERVICE_TOKEN = os.getenv("VERISAFE_SERVICE_TOKEN", "")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "storages",  # For boto3 aws
    "channels",
    "users",
    "posts",
    "communities",
    "dmessages",
    "utils",
    "conversations",
    "websocket_chat",
    "event_bus",
]

# Django Channels Configuration
ASGI_APPLICATION = "chirp.asgi.application"

# Channel Layers for Redis
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1")],
        },
    },
}

# Rabbit mq setup
RABBITMQ_USER = os.getenv("RABBITMQ_USER", "rabbit" )
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD", "zero")
RABBITMQ_HOST = os.getenv("RABBITMQ_HOST", "ds")
RABBITMQ_PORT = os.getenv("RABBITMQ_PORT", "5672")
RABBITMQ_VHOST = os.getenv("RABBITMQ_VHOST", "/")


# WebSocket Security Settings
WEBSOCKET_RATE_LIMIT = 100
WEBSOCKET_HEARTBEAT_INTERVAL = 30
WEBSOCKET_CONNECTION_TIMEOUT = 300
WEBSOCKET_MAX_MESSAGE_SIZE = 1024 * 1024

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "chirp.verisafe_authentication.VerisafeAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "chirp.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 50,
}

# JWT Configuration
try:
    from decouple import config

    SECRET_KEY = config(
        "SECRET_KEY",
        default="django-insecure-_27eto_6&*cz6cx26valns6lqv*v4am224r3j9y5@hoz*58=_-",
    )
    JWT_PUBLIC_KEY = config(
        "JWT_PUBLIC_KEY", default="test_jwt_secret_key_for_chirp_testing"
    )
except ImportError:
    # Fallback for tests or when decouple is not available
    JWT_PUBLIC_KEY = "test_jwt_secret_key_for_chirp_testing"

# JWT Testing Configuration
JWT_TEST_SECRET = "test_jwt_secret_key_for_chirp_testing"
JWT_ALGORITHM = "HS256"

# For production, you would configure these for your external JWT provider:
# JWT_PUBLIC_KEY = 'your_production_rsa_public_key'
# JWT_ALGORITHM = 'RS256'
# Note: For HS256 (symmetric), use same secret for signing and verification
# For RS256 (asymmetric), use private key for signing, public key for verification

# Verisafe Integration
VERISAFE_BASE_URL = os.getenv("VERISAFE_BASE_URL", "https://api.opencrafts.io"                    
  )
VERISAFE_SERVICE_TOKEN = os.getenv("VERISAFE_SERVICE_TOKEN", "")

# Verisafe JWT Configuration
VERISAFE_API_SECRET = os.getenv("VERISAFE_API_SECRET", "super-secret-token")
VERISAFE_ISSUER = os.getenv("VERISAFE_ISSUER", "https://verisafe.opencrafts.io/")
VERISAFE_AUDIENCE = os.getenv("VERISAFE_AUDIENCE", "https://academia.opencrafts.io/")

# Cache configuration for user data
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),
    }
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "chirp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "chirp.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "chirp"),
        "USER": os.getenv("DB_USER", "mr_app"),
        "PASSWORD": os.getenv("DB_PASSWORD", "mr_app"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", None)
assert AWS_ACCESS_KEY_ID is not None, "AWS_ACCESS_KEY_ID was not set in .env!"

AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", None)
assert AWS_SECRET_ACCESS_KEY is not None, "AWS_SECRET_ACCESS_KEY was not set in .env!"  # ← FIXED

AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", None)
assert AWS_STORAGE_BUCKET_NAME is not None, "AWS_STORAGE_BUCKET_NAME was not set in .env!"  # ← FIXED

AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", None)
assert AWS_S3_REGION_NAME is not None, "AWS_S3_REGION_NAME was not set in .env!"


AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

print(AWS_S3_REGION_NAME)

# For serving static files directly from S3
AWS_S3_URL_PROTOCOL = "https:"
AWS_S3_USE_SSL = True
AWS_S3_VERIFY = True

STATIC_URL = "static/"
MEDIA_URL = "/media/"

ENVIRONMENT = os.getenv("ENVIRONMENT", "dev")

STORAGE_LOCATION = "chirp-media"

if ENVIRONMENT == "prod":
    STORAGE_LOCATION = "chirp-media"
elif ENVIRONMENT == "staging":
    STORAGE_LOCATION = "qa-chirp-media"
else:
    STORAGE_LOCATION = "dev-chirp-media"

print(AWS_S3_CUSTOM_DOMAIN)

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "location": STORAGE_LOCATION,
            "querystring_auth": False,
            "default_acl": None,
            "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            "url_protocol": "https:",
            "signature_version": "s3v4",
            "querystring_expire": 3600,
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "location": "static",
            "querystring_auth": False,
            "default_acl": None,
            "signature_version": "s3v4",
            "querystring_expire": 3600,
            "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            "url_protocol": AWS_S3_URL_PROTOCOL,
        },
    },
}


# File upload settings for large images
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# HTTPS Configuration
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_TLS = os.environ.get("USE_TLS", "False").lower() == "true"
