# Generated by Django 5.2.9 on 2026-01-17 14:46

import utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=models.FileField(upload_to=utils.uploads.get_post_attachment_path),
        ),
    ]
