# Generated by Django 6.0.4 on 2026-05-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_banner_and_more'),
        ('posts', '0003_alter_attachment_file'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='post_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community'], name='post_community_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author'], name='post_author_idx'),
        ),
    ]