# Generated by Django 5.2.3 on 2025-07-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='Post',
        ),
    ]
