# Generated by Django 5.2.3 on 2025-08-24 21:12

from django.db import migrations, models
import django.db.models.deletion


def set_default_group(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    Group = apps.get_model('groups', 'Group')

    # Get or create the default group
    default_group, created = Group.objects.get_or_create(
        id=1,
        defaults={
            'name': 'General',
            'description': 'General community for all posts',
            'creator_id': 'system'
        }
    )

    # Update any posts without a group to use the default
    Post.objects.filter(group__isnull=True).update(group=default_group)


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('posts', '0008_alter_post_options_post_group'),
    ]

    operations = [
        migrations.RunPython(set_default_group, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='groups.group'),
        ),
    ]
