# Generated by Django 5.2.6 on 2025-09-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0014_postview_postvotes_alter_commentlike_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
