# Generated by Django 5.2.6 on 2025-09-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0016_post_comment_count_alter_post_content_commentvote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postvotes",
            name="value",
            field=models.SmallIntegerField(
                choices=[(1, "Upvote"), (-1, "Downvote")], null=True
            ),
        ),
    ]
