# Generated by Django 5.2.6 on 2025-09-28 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0014_remove_group_creator_remove_groupmembership_group_and_more"),
        ("posts", "0017_alter_postvotes_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_posts",
                to="groups.community",
            ),
        ),
    ]
