# Generated by Django 5.2.6 on 2025-09-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0018_alter_post_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="group",
            new_name="community",
        ),
    ]
