# Generated by Django 5.2.6 on 2025-09-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_url_user_full_name_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vibe_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
