# Generated by Django 5.2.6 on 2025-09-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_vibe_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vibe_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
