# Generated by Django 5.2.6 on 2025-09-25 20:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_vibe_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id_new",
            field=models.UUIDField(
                default=uuid.UUID("61a68264-0baf-463c-af55-853f857fab0d"), unique=True
            ),
        ),
    ]
