# Generated by Django 5.2.6 on 2025-09-25 20:32

from django.db import migrations
import uuid


def populate_user_ids(apps, schema_editor):
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        try:
            user.user_id_new = uuid.UUID(user.user_id)
        except Exception:
            user.user_id_new = uuid.uuid4()
        finally:
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_user_id_new"),
    ]

    operations = [
        migrations.RunPython(populate_user_ids)
    ]
