# Generated by Django 5.2.6 on 2025-09-25 20:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_populate_user_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id_new",
            field=models.UUIDField(
                default=uuid.uuid4(),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
