# Generated by Django 5.2.6 on 2025-09-25 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_user_user_id_alter_user_user_id_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_id_new",
        ),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("34253ec2-d180-4573-a969-fe99c2d90573"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
