# Generated by Django 5.2.6 on 2025-09-25 21:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_user_user_id_new_user_user_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_user_na_108efb_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_name",
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="Anonymous User", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.uuid4(),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
