# Generated by Django 5.2.6 on 2025-09-26 21:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_user_users_user_na_108efb_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("ac7a503f-c464-444c-bf66-dd07cd731b31"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
