# Generated by Django 5.2.6 on 2025-09-26 22:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("c1f8c1d2-bf2b-4b8c-a9bb-c46a6b640b88"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
