# Generated by Django 5.2.6 on 2025-09-26 22:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("e8e249ca-037b-4d46-92dc-470d6e8c2098"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
