# Generated by Django 5.2.6 on 2025-09-27 00:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("742198aa-0e8d-4d66-9854-27a3f6be5614"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
