# Generated by Django 5.2.6 on 2025-09-27 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(
                default=uuid.UUID("6170b37b-c502-4715-bb80-2c21e9c8368d"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
