# Generated by Django 5.2.9 on 2026-01-17 14:40

import utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="banner",
            field=models.ImageField(
                height_field="banner_height",
                null=True,
                upload_to=utils.uploads.get_community_banner_path,
                width_field="banner_width",
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="profile_picture",
            field=models.ImageField(
                height_field="profile_picture_height",
                null=True,
                upload_to=utils.uploads.get_community_profile_path,
                width_field="profile_picture_width",
            ),
        ),
    ]
