# Generated by Django 5.2.3 on 2025-08-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin_names',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='group',
            name='banned_user_names',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='group',
            name='banner',
            field=models.ImageField(blank=True, help_text='Community banner image (wide image recommended)', null=True, upload_to='groups/banners/'),
        ),
        migrations.AddField(
            model_name='group',
            name='creator_name',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, help_text='Community logo (square image recommended)', null=True, upload_to='groups/logos/'),
        ),
        migrations.AddField(
            model_name='group',
            name='member_names',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='group',
            name='moderator_names',
            field=models.JSONField(default=list),
        ),
    ]
