# Generated by Django 5.2.3 on 2025-08-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_admin_names_group_banned_user_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='group',
            name='admin_names',
        ),
    ]
