# Generated by Django 5.2.3 on 2025-08-26 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20250824_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('created_by_name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expiration_hours', models.IntegerField(choices=[(72, '72 hours'), (168, '1 week')], default=72)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_by', models.CharField(blank=True, max_length=255, null=True)),
                ('used_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='groups.group')),
            ],
            options={
                'db_table': 'invite_links',
            },
        ),
    ]
