# Generated by Django 5.2.3 on 2025-08-30 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_invitelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='group',
            name='logo',
        ),
        migrations.CreateModel(
            name='GroupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Logo'), ('banner', 'Banner')], default='logo', max_length=10)),
                ('file', models.ImageField(upload_to='groups/images/')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='groups.group')),
            ],
            options={
                'unique_together': {('group', 'image_type')},
            },
        ),
    ]
