# Generated by Django 5.2.6 on 2025-09-14 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_remove_group_banner_remove_group_logo_groupimage'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('moderator', 'Moderator'), ('member', 'Member'), ('banned', 'Banned')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='users.user')),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'role'], name='groups_grou_group_i_0277c0_idx'), models.Index(fields=['user', 'role'], name='groups_grou_user_id_a744c2_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
