# Generated by Django 5.2.6 on 2025-09-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0012_groupmembership_banned_groupmembership_banned_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupImage",
        ),
    ]
