# Generated by Django 5.2.6 on 2025-09-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0014_remove_group_creator_remove_groupmembership_group_and_more"),
        ("posts", "0018_alter_post_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="GroupInvite",
        ),
        migrations.DeleteModel(
            name="GroupMembership",
        ),
        migrations.AddIndex(
            model_name="communitymembership",
            index=models.Index(
                fields=["community", "role"], name="groups_comm_communi_56801f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitymembership",
            index=models.Index(
                fields=["user", "role"], name="groups_comm_user_id_71d579_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communitymembership",
            unique_together={("community", "user")},
        ),
    ]
