# Generated by Django 5.2.6 on 2025-09-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0015_delete_group_delete_groupinvite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitymembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("super-mod", "Super Moderator"),
                    ("moderator", "Moderator"),
                    ("member", "Member"),
                ],
                max_length=20,
            ),
        ),
    ]
