# Generated by Django 5.2.3 on 2025-08-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at', '-created_at']},
        ),
    ]
