# Generated by Django 5.2.9 on 2026-01-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked_user', 'block_type')},
        ),
    ]
