# Generated by Django 5.2.3 on 2025-08-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmessages', '0004_messageattachment_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
