# Generated by Django 5.2.6 on 2025-09-14 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmessages', '0005_alter_message_is_deleted_alter_message_is_read'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='users.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='users.user'),
        ),
    ]
