from django.urls import path

from posts.views import (
    CommentDestroyView,
    CommentListCreateView,
    CommentRetrieveView,
    DestroyPostView,
    ListPostAttachmentsView,
    ListPostView,
    PostAttachmentCreateView,
    PostCreateView,
    PostListByCommunityView,
    PostSearchView,
    PostVoteDeleteView,
    PostVoteView,
    PostsFeedView,
    RecordPostViewerView,
    RetrievePostByAuthorView,
    RetrievePostByIDView,
)

urlpatterns = [
    path(
        "create/",
        PostCreateView.as_view(),
        name="post-create",
    ),
    path(
        "attachment/create/",
        PostAttachmentCreateView.as_view(),
        name="post-attachment-create",
    ),
    path(
        "<int:post_id>/attachments",
        ListPostAttachmentsView.as_view(),
        name="post-attachment-view",
    ),
    path(
        "feed/",
        PostsFeedView.as_view(),
        name="post-feed",
    ),
    path(
        "all/",
        ListPostView.as_view(),
        name="post-list",
    ),
    path(
        "<int:id>/details/",
        RetrievePostByIDView.as_view(),
        name="get-post-by-id",
    ),
    path(
        "by/<uuid:author>/",
        RetrievePostByAuthorView.as_view(),
        name="get-post-by-author",
    ),
    path(
        "from/<int:community_id>/",
        PostListByCommunityView.as_view(),
        name="get-post-by-community",
    ),
    path(
        "search/",
        PostSearchView.as_view(),
        name="search-for-post",
    ),
    path(
        "<int:id>/delete/",
        DestroyPostView.as_view(),
        name="delete-post",
    ),
    # Post view metrics
    path(
        "<int:id>/viewed/",
        RecordPostViewerView.as_view(),
        name="record-post-as-viewed",
    ),
    # Post votes
    path(
        "<int:post_id>/vote/",
        PostVoteView.as_view(),
        name="post-vote",
    ),
    path(
        "<int:post_id>/vote/redact/",
        PostVoteDeleteView.as_view(),
        name="post-vote-redact",
    ),
    # Comments
    path(
        "<int:post_id>/comments/",
        CommentListCreateView.as_view(),
        name="comments-list-create",
    ),
    path(
        "comments/<int:id>/",
        CommentRetrieveView.as_view(),
        name="comment-detail",
    ),
    path(
        "comments/<int:id>/delete/",
        CommentDestroyView.as_view(),
        name="delete-comment-by-id",
    ),
]
