# Generated by Django 5.2.3 on 2025-07-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweetreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tweet_images/'),
        ),
    ]
