# Generated by Django 5.2.3 on 2025-08-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_options_group_banned_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rules',
            field=models.JSONField(default=list),
        ),
    ]
