# Generated by Django 5.2.6 on 2025-09-27 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0010_populate_group_memberships"),
        ("users", "0016_alter_user_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="rules",
            new_name="guidelines",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="is_private",
            new_name="private",
        ),
        migrations.RemoveField(
            model_name="group",
            name="banned_user_names",
        ),
        migrations.RemoveField(
            model_name="group",
            name="banned_users",
        ),
        migrations.RemoveField(
            model_name="group",
            name="creator_id",
        ),
        migrations.RemoveField(
            model_name="group",
            name="creator_name",
        ),
        migrations.RemoveField(
            model_name="group",
            name="member_names",
        ),
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.RemoveField(
            model_name="group",
            name="moderator_names",
        ),
        migrations.RemoveField(
            model_name="group",
            name="moderators",
        ),
        migrations.AddField(
            model_name="group",
            name="banned_users_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="banner",
            field=models.ImageField(
                height_field="banner_height",
                null=True,
                upload_to="groups/banners/",
                width_field="banner_width",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="banner_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="banner_width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_creators",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="member_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="moderator_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="monthly_visitor_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="nsfw",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="group",
            name="profile_picture",
            field=models.ImageField(
                height_field="profile_picture_height",
                null=True,
                upload_to="groups/profile_pictures/",
                width_field="profile_picture_width",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="profile_picture_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="profile_picture_width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="group",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="group",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="private",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="weekly_visitor_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
