# Generated by Django 5.2.6 on 2025-09-28 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0011_rename_rules_group_guidelines_and_more"),
        ("users", "0017_alter_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmembership",
            name="banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="banned_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="banned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banned_memberships",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="banning_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_memberships",
                to="groups.group",
            ),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="role",
            field=models.CharField(
                choices=[("moderator", "Moderator"), ("member", "Member")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="groupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_members",
                to="users.user",
            ),
        ),
        migrations.DeleteModel(
            name="GroupPost",
        ),
    ]
